from __future__ import annotations

from datetime import datetime
from types import TracebackType
from typing import Any, Protocol, Self
from uuid import UUID

from apps.engine.domain.models import TaskExecution, WorkflowRuntime


class EngineStore(Protocol):
    async def workflow_exists(self, execution_id: UUID) -> bool: ...
    async def add_runtime(self, runtime: WorkflowRuntime) -> None: ...
    async def flush(self) -> None: ...
    async def get_runtime(
        self, execution_id: UUID, *, for_update: bool = False
    ) -> WorkflowRuntime | None: ...
    async def save_runtime(self, runtime: WorkflowRuntime) -> None: ...
    async def add_task(self, task: TaskExecution) -> None: ...
    async def get_task(
        self, task_execution_id: UUID, *, for_update: bool = False
    ) -> TaskExecution | None: ...
    async def get_latest_tasks(self, execution_id: UUID) -> dict[str, TaskExecution]: ...
    async def save_task(self, task: TaskExecution) -> None: ...
    async def add_result(self, task: TaskExecution, output: Any) -> None: ...
    async def get_outputs(self, execution_id: UUID) -> dict[str, Any]: ...
    async def add_outbox(
        self, topic: str, key: str, message_id: UUID, payload: dict[str, object]
    ) -> None: ...
    async def add_processed_message(self, message_id: UUID, consumer: str) -> bool: ...


class EngineUnitOfWork(Protocol):
    store: EngineStore

    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
    async def commit(self) -> None: ...


class DueRetryFinder(Protocol):
    async def find_due_retry_ids(self, now: datetime, limit: int = 100) -> list[UUID]: ...
